Repository ASNeG/OpcUaStack, pull requests merged in 2019-03, with the labels that each got.

#120 Improve perfomance of Inforamtion Model
  .gitignore
  CHANGELOG.rst
  src/OpcUaStackServer/AddressSpaceModel/ReferenceItem.cpp
  src/OpcUaStackServer/AddressSpaceModel/ReferenceItem.h
  src/OpcUaStackServer/AddressSpaceModel/ReferenceItemMap.cpp
  src/OpcUaStackServer/AddressSpaceModel/ReferenceItemMap.h
  src/OpcUaStackServer/InformationModel/InformationModel.cpp
  src/OpcUaStackServer/InformationModel/InformationModel.h
  src/OpcUaStackServer/InformationModel/InformationModelAccess.cpp
  src/OpcUaStackServer/InformationModel/InformationModelAccess.h
  src/OpcUaStackServer/InformationModel/InformationModelManager.cpp
  src/OpcUaStackServer/InformationModel/InformationModelManager.h
  src/OpcUaStackServer/NodeSet/NodeSetXmlParser.cpp
  src/OpcUaStackServer/NodeSet/NodeSetXmlParser.h
  src/OpcUaStackServer/ServiceSet/ViewService.cpp
  src/OpcUaStackServer/ServiceSetApplication/ApplicationService.cpp
  tst/OpcUaStackServer/AddressSpaceModel/RefernceItemMap_t.cpp
  tst/data/opc.ua.roby_save.xml
Labels: enhancement

#132 Fix calling stop monitored item callback.
  CHANGELOG.rst
  src/OpcUaStackServer/ServiceSet/MonitorManager.cpp
  src/OpcUaStackServer/ServiceSet/MonitorManager.h
  tst/OpcUaStackServer/ServiceSet/MonitorManager_t.cpp
Labels: bug

#142 118 remove unused classes
  CHANGELOG.rst
  src/OpcUaStackCore/Base/Pool.cpp
  src/OpcUaStackCore/Base/Pool.h
  src/OpcUaStackCore/Base/PoolBase.cpp
  src/OpcUaStackCore/Base/PoolBase.h
  tst/OpcUaStackCore/Base/Pool_t.cpp
Labels: enhancement

#143 Replace cancel command by close command.
  src/OpcUaStackCore/SecureChannel/SecureChannelServer.cpp
Labels: bug

#145 117 replace class condition process
  src/CMakeLists.txt
  src/OpcUaClient/ClientService/ClientServiceBrowse.cpp
  src/OpcUaClient/ClientService/ClientServiceBrowse.h
  src/OpcUaClient/ClientService/ClientServiceNodeSetFilter.cpp
  src/OpcUaClient/ClientService/ClientServiceNodeSetFilter.h
  src/OpcUaClient/ClientService/ClientServiceNodeSetServer.cpp
  src/OpcUaClient/ClientService/ClientServiceNodeSetServer.h
  src/OpcUaGenerator/CMakeLists.txt
  src/OpcUaStackClient/ServiceSet/AttributeService.cpp
  src/OpcUaStackClient/ServiceSet/DiscoveryService.cpp
  src/OpcUaStackClient/ServiceSet/MethodService.cpp
  src/OpcUaStackClient/ServiceSet/MonitoredItemService.cpp
  src/OpcUaStackClient/ServiceSet/NodeManagementService.cpp
  src/OpcUaStackClient/ServiceSet/QueryService.cpp
  src/OpcUaStackClient/ServiceSet/SubscriptionServiceBase.cpp
  src/OpcUaStackClient/ServiceSet/ViewService.cpp
  src/OpcUaStackCore/Base/ConditionBool.cpp
  src/OpcUaStackCore/Base/ConditionBool.h
  src/OpcUaStackCore/Base/ConditionProcess.cpp
  src/OpcUaStackCore/Base/ConditionProcess.h
  src/OpcUaStackCore/ServiceSet/ServiceTransaction.cpp
  src/OpcUaStackCore/ServiceSet/ServiceTransaction.h
  src/OpcUaStackPubSub/CMakeLists.txt
  src/OpcUaStackServer/Application/Application.cpp
  src/OpcUaStackServer/CMakeLists.txt
  src/OpcUaStackServer/ServiceSet/SessionManager.cpp
  src/OpcUaStackServer/ServiceSet/SessionManager.h
  tst/OpcUaStackClient/ServiceSet/ServiceSetManagerAsyncReal_Method_t.cpp
  tst/OpcUaStackClient/ServiceSet/ServiceSetManagerAsyncReal_MonitoredItem_t.cpp
  tst/OpcUaStackClient/ServiceSet/ServiceSetManagerSyncReal_Method_t.cpp
  tst/OpcUaStackClient/ServiceSet/ServiceSetManagerSyncReal_MonitoredItem_t.cpp
  tst/OpcUaStackClient/ValueBasedInterface/VBIAsyncReal_Attribute_GetEndpointRequest.cpp
  tst/OpcUaStackClient/ValueBasedInterface/VBIAsyncReal_Attribute_SignAndEncrypt.cpp
  tst/OpcUaStackClient/ValueBasedInterface/VBIAsyncReal_Attribute_t.cpp
  tst/OpcUaStackClient/ValueBasedInterface/VBISyncReal_Attribute_t.cpp
  tst/OpcUaStackClient/ValueBasedInterface/VBISyncReal_MonitoredItem_t.cpp
Labels: enhancement

#147 146 offer namespace 1 in v3
  src/OpcUaStackCore/SecureChannel/SecureChannelServer.cpp
  tst/OpcUaStackClient/ServiceSet/ServiceSetManagerAsyncReal_Method_t.cpp
  tst/OpcUaStackClient/ServiceSet/ServiceSetManagerAsyncReal_MonitoredItem_t.cpp
  tst/OpcUaStackClient/ServiceSet/ServiceSetManagerSyncReal_Method_t.cpp
  tst/OpcUaStackClient/ServiceSet/ServiceSetManagerSyncReal_MonitoredItem_t.cpp
  tst/OpcUaStackClient/ValueBasedInterface/VBIAsyncReal_Attribute_t.cpp
  tst/OpcUaStackClient/ValueBasedInterface/VBISyncReal_Attribute_t.cpp
  tst/OpcUaStackClient/ValueBasedInterface/VBISyncReal_MonitoredItem_t.cpp
Labels: enhancement

#144 added server namesapce 1
  CHANGELOG.rst
  src/OpcUaProjectBuilder/ProjectTemplate/src/ProjectName/Config/Opc.Ua.NodeSet.ASNeGServer.xml
  src/OpcUaProjectBuilder/ProjectTemplate/src/ProjectName/Config/OpcUaServer.xml
Labels: bug

#141 allow relative install path
  CHANGELOG.rst
  build.sh
Labels: bug, enhancement

#160 Added missing transaction handling.
  CHANGELOG.rst
  build.sh
  docs/source/_templates/layout.html
  docs/source/getting_started/hello_world.rst
  docs/source/getting_started/installation.rst
  src/OpcUaStackClient/ApplicationUtility/DiscoveryClientRegisteredServers.cpp
  src/OpcUaStackCore/BuildInTypes/OpcUaDataValue.cpp
  src/OpcUaStackCore/SecureChannel/SecureChannelClient.cpp
  src/OpcUaStackCore/SecureChannel/SecureChannelServer.cpp
  src/OpcUaStackServer/Application/Application.cpp
  src/OpcUaStackServer/ServiceSet/MonitorManager.cpp
  src/OpcUaStackServer/ServiceSet/MonitorManager.h
  tst/OpcUaStackClient/ServiceSet/ServiceSetManagerAsyncReal_Method_t.cpp
  tst/OpcUaStackClient/ServiceSet/ServiceSetManagerAsyncReal_MonitoredItem_t.cpp
  tst/OpcUaStackClient/ServiceSet/ServiceSetManagerSyncReal_Method_t.cpp
  tst/OpcUaStackClient/ServiceSet/ServiceSetManagerSyncReal_MonitoredItem_t.cpp
  tst/OpcUaStackClient/ValueBasedInterface/VBIAsyncReal_Attribute_t.cpp
  tst/OpcUaStackClient/ValueBasedInterface/VBISyncReal_Attribute_t.cpp
  tst/OpcUaStackClient/ValueBasedInterface/VBISyncReal_MonitoredItem_t.cpp
  tst/OpcUaStackServer/ServiceSet/MonitorManager_t.cpp
Labels: bug

#82 Document the new application interface
  CHANGELOG.rst
  README.rst
  docs/source/1_getting_started/_index.rst
  docs/source/1_getting_started/add_new_server.png
  docs/source/1_getting_started/data_access_view_1.png
  docs/source/1_getting_started/hello_world.rst
  docs/source/1_getting_started/helloworld.zip
  docs/source/1_getting_started/installation.rst
  docs/source/1_getting_started/overview.rst
  docs/source/2_user_app/_index.rst
  docs/source/2_user_app/creating.rst
  docs/source/2_user_app/distribution.rst
  docs/source/3_development/_index.rst
  docs/source/3_development/access_control_example.zip
  docs/source/3_development/data_access.rst
  docs/source/3_development/data_access_example.zip
  docs/source/3_development/discovery_process.rst
  docs/source/3_development/events.rst
  docs/source/3_development/history_data_acces
  docs/source/3_development/methods.rst
  docs/source/3_development/node_management.rst
  docs/source/3_development/security.rst
  docs/source/3_development/session_and_access_control.rst
  docs/source/4_contribution/_index.rst
  docs/source/conf.py
  docs/source/contents.rst
  docs/source/glossary.rst
  docs/source/index.rst
  src/OpcUaProjectBuilder/ProjectTemplate/build.sh
  src/OpcUaStackServer/ServiceSetApplication/RegisterForwardNode.h
Labels: doc, enhancement

#162 155 added historical access vbi
  CHANGELOG.rst
  src/CMakeLists.txt
  src/OpcUaStackClient/ValueBasedInterface/HistoryRead.cpp
  src/OpcUaStackClient/ValueBasedInterface/HistoryRead.h
  src/OpcUaStackClient/ValueBasedInterface/VBIClient.cpp
  src/OpcUaStackClient/ValueBasedInterface/VBIClient.h
  src/OpcUaStackClient/ValueBasedInterface/VBIContext.cpp
  src/OpcUaStackClient/ValueBasedInterface/VBIContext.h
  src/OpcUaStackClient/ValueBasedInterface/VBITransaction.cpp
  src/OpcUaStackClient/ValueBasedInterface/VBITransaction.h
  xx
Labels: enhancement

#165 Rework discovery client register service.
  src/OpcUaStackClient/ApplicationUtility/DiscoveryClientRegisteredServers.cpp
  src/OpcUaStackClient/ApplicationUtility/DiscoveryClientRegisteredServers.h
Labels: enhancement
